/**
 * Host-only workspace resource prefs (Settings → Resources).
 * Persisted under state/private; applied via generated compose override.
 */
import fs from "node:fs";
import path from "node:path";
import { PRIVATE_STATE_DIR, ROOT, STATE_DIR } from "./paths.js";

export const RESOURCES_CONFIG_PATH = path.join(
  PRIVATE_STATE_DIR,
  "resources.json",
);
/** Writable override path (app bundle ROOT may be read-only when packaged). */
export const RESOURCES_COMPOSE_PATH = process.env.SAARIDGE_RESOURCES_COMPOSE
  ? path.resolve(process.env.SAARIDGE_RESOURCES_COMPOSE)
  : path.join(STATE_DIR, "docker-compose.resources.yml");

/** Allowed presets for the Settings UI (plus free-form validation). */
export const RESOURCE_PRESETS = {
  memory: ["1g", "2g", "4g", "8g", "16g"],
  cpus: ["1", "2", "4", "6", "8"],
  shmSize: ["512m", "1g", "2g"],
  tmpfsSize: ["256m", "512m", "1g", "2g"],
  resolution: ["1280x720x24", "1920x1080x24", "2560x1440x24", "3840x2160x24"],
};

export const DEFAULT_RESOURCES = Object.freeze({
  memory: "4g",
  cpus: "2",
  shmSize: "1g",
  tmpfsSize: "512m",
  resolution: "1920x1080x24",
});

const SIZE_RE = /^(\d+(?:\.\d+)?)(b|k|kb|m|mb|g|gb|t|tb)$/i;
const RESOLUTION_RE = /^(\d{3,5})x(\d{3,5})x(16|24)$/;

const normalizeSize = (value, field) => {
  const raw = String(value ?? "").trim().toLowerCase();
  if (!SIZE_RE.test(raw)) {
    throw new Error(`Invalid ${field}: use values like 512m or 4g`);
  }
  return raw.replace(/b$/i, "");
};

const normalizeCpus = (value) => {
  const n = Number(value);
  if (!Number.isFinite(n) || n < 0.5 || n > 32) {
    throw new Error("CPUs must be a number between 0.5 and 32");
  }
  // Compose accepts decimals; keep compact string without trailing zeros noise.
  const s = String(Math.round(n * 100) / 100);
  return s;
};

const normalizeResolution = (value) => {
  const raw = String(value ?? "").trim().toLowerCase();
  if (!RESOLUTION_RE.test(raw)) {
    throw new Error("Resolution must look like 1920x1080x24");
  }
  return raw;
};

export const normalizeResources = (input = {}) => {
  const src = input && typeof input === "object" ? input : {};
  return {
    memory: normalizeSize(src.memory ?? DEFAULT_RESOURCES.memory, "memory"),
    cpus: normalizeCpus(src.cpus ?? DEFAULT_RESOURCES.cpus),
    shmSize: normalizeSize(src.shmSize ?? DEFAULT_RESOURCES.shmSize, "shmSize"),
    tmpfsSize: normalizeSize(
      src.tmpfsSize ?? DEFAULT_RESOURCES.tmpfsSize,
      "tmpfsSize",
    ),
    resolution: normalizeResolution(
      src.resolution ?? DEFAULT_RESOURCES.resolution,
    ),
  };
};

const ensurePrivateDir = () => {
  fs.mkdirSync(PRIVATE_STATE_DIR, { recursive: true });
};

export const readResources = () => {
  try {
    if (!fs.existsSync(RESOURCES_CONFIG_PATH)) {
      return { ...DEFAULT_RESOURCES };
    }
    const raw = JSON.parse(fs.readFileSync(RESOURCES_CONFIG_PATH, "utf8"));
    return normalizeResources(raw);
  } catch {
    return { ...DEFAULT_RESOURCES };
  }
};

export const saveResources = (patch = {}) => {
  const current = readResources();
  const next = normalizeResources({ ...current, ...patch });
  ensurePrivateDir();
  fs.writeFileSync(
    RESOURCES_CONFIG_PATH,
    `${JSON.stringify(next, null, 2)}\n`,
    "utf8",
  );
  return next;
};

/** Render compose override YAML (no dependency on a YAML library). */
export const renderResourcesComposeOverride = (prefs = readResources()) => {
  const p = normalizeResources(prefs);
  return `# Generated by Saaridge — do not edit by hand.
# Managed from Settings → Resources (${RESOURCES_CONFIG_PATH}).
services:
  agent-box:
    mem_limit: ${p.memory}
    cpus: ${p.cpus}
    shm_size: "${p.shmSize}"
    tmpfs:
      - /tmp:size=${p.tmpfsSize},mode=1777
    environment:
      RESOLUTION: ${p.resolution}
`;
};

/** Write override file so `docker compose` picks up current prefs. */
export const writeResourcesComposeOverride = (prefs = readResources()) => {
  const normalized = normalizeResources(prefs);
  const body = renderResourcesComposeOverride(normalized);
  fs.mkdirSync(path.dirname(RESOURCES_COMPOSE_PATH), { recursive: true });
  fs.writeFileSync(RESOURCES_COMPOSE_PATH, body, "utf8");
  return { prefs: normalized, path: RESOURCES_COMPOSE_PATH };
};

export const resourcesStatus = () => {
  const resources = readResources();
  return {
    resources,
    presets: RESOURCE_PRESETS,
    defaults: { ...DEFAULT_RESOURCES },
    /** False until the user saves prefs (first-run wizard or Settings). */
    configured: fs.existsSync(RESOURCES_CONFIG_PATH),
    configPath: RESOURCES_CONFIG_PATH,
    composePath: RESOURCES_COMPOSE_PATH,
    note: "Applying restarts the workspace container. Limits cannot exceed Docker Desktop → Resources.",
  };
};
