#!/usr/bin/env bash
# Virtual speaker + WebSocket audio stream for the host viewer.
# Idempotent: safe for audio-watchdog to call repeatedly.
# Usage: start-audio.sh [--check]
set -uo pipefail

export HOME="${HOME:-/home/browser}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-browser}"
export PULSE_RUNTIME_PATH="${PULSE_RUNTIME_PATH:-$XDG_RUNTIME_DIR/pulse}"
export PULSE_STATE_PATH="${PULSE_STATE_PATH:-$HOME/.config/pulse}"
export AUDIO_WS_PORT="${AUDIO_WS_PORT:-6082}"

mkdir -p "$XDG_RUNTIME_DIR" "$PULSE_RUNTIME_PATH" "$PULSE_STATE_PATH"
chmod 700 "$XDG_RUNTIME_DIR" || true

is_live_pulse() {
  local pid state
  for pid in $(pgrep -u "$(id -u)" -x pulseaudio 2>/dev/null || true); do
    state="$(ps -o state= -p "$pid" 2>/dev/null | tr -d '[:space:]')"
    if [[ -n "$state" && "$state" != "Z" ]]; then
      return 0
    fi
  done
  return 1
}

has_socket() {
  [[ -S "${PULSE_RUNTIME_PATH}/native" ]]
}

has_sink() {
  export PULSE_SERVER="unix:${PULSE_RUNTIME_PATH}/native"
  pactl --server="$PULSE_SERVER" list short sinks 2>/dev/null | grep -q onebridge
}

stream_listening() {
  ss -lnt 2>/dev/null | grep -q ":${AUDIO_WS_PORT} "
}

audio_healthy() {
  is_live_pulse && has_socket && has_sink && stream_listening
}

ensure_pulse_client_conf() {
  mkdir -p "$PULSE_STATE_PATH"
  cat >"${PULSE_STATE_PATH}/client.conf" <<EOF
# Generated by start-audio.sh — Chromium/zygote find Pulse without PULSE_SERVER.
default-server = unix:${PULSE_RUNTIME_PATH}/native
autospawn = no
EOF
}

if [[ "${1:-}" == "--check" ]]; then
  if audio_healthy; then
    exit 0
  fi
  exit 1
fi

# Already good — refresh client.conf, do not bounce Pulse / kill the WS.
if audio_healthy; then
  export PULSE_SERVER="unix:${PULSE_RUNTIME_PATH}/native"
  ensure_pulse_client_conf
  pactl --server="$PULSE_SERVER" set-default-sink onebridge 2>/dev/null || true
  pactl --server="$PULSE_SERVER" set-sink-mute onebridge 0 2>/dev/null || true
  pactl --server="$PULSE_SERVER" set-sink-volume onebridge 100% 2>/dev/null || true
  echo "[start-audio] OK already (PULSE_SERVER=$PULSE_SERVER :${AUDIO_WS_PORT})"
  exit 0
fi

# --- heal Pulse ---
if ! is_live_pulse || ! has_socket; then
  pkill -u "$(id -u)" -x pulseaudio 2>/dev/null || true
  sleep 0.3
  pulseaudio --daemonize=yes --exit-idle-time=-1 --disallow-exit \
    --log-target=file:/tmp/pulseaudio.log --log-level=info \
    >/tmp/pulseaudio-start.log 2>&1 || true
  sleep 0.8
fi

export PULSE_SERVER="unix:${PULSE_RUNTIME_PATH}/native"
for _ in $(seq 1 20); do
  if has_socket; then
    break
  fi
  sleep 0.25
done

if ! has_socket; then
  echo "[start-audio] ERROR: Pulse socket missing at ${PULSE_RUNTIME_PATH}/native" >&2
  tail -40 /tmp/pulseaudio.log 2>/dev/null >&2 || true
  tail -40 /tmp/pulseaudio-start.log 2>/dev/null >&2 || true
  exit 1
fi

# --- heal null sink (only recreate if missing) ---
if ! has_sink; then
  pactl --server="$PULSE_SERVER" unload-module module-null-sink 2>/dev/null || true
  pactl --server="$PULSE_SERVER" load-module module-null-sink sink_name=onebridge \
    sink_properties=device.description=OneBridge_Speaker >/tmp/pulse-sink.log 2>&1 || true
fi

pactl --server="$PULSE_SERVER" set-default-sink onebridge 2>/dev/null || true
pactl --server="$PULSE_SERVER" set-default-source onebridge.monitor 2>/dev/null || true
pactl --server="$PULSE_SERVER" set-sink-mute onebridge 0 2>/dev/null || true
pactl --server="$PULSE_SERVER" set-sink-volume onebridge 100% 2>/dev/null || true

# So Chromium finds Pulse even if launched without PULSE_SERVER in the environment.
ensure_pulse_client_conf
chown -R "$(id -u):$(id -g)" "$PULSE_STATE_PATH" 2>/dev/null || true

pactl --server="$PULSE_SERVER" list short sinks >/tmp/pulse-sinks.txt 2>&1 || true
if ! grep -q onebridge /tmp/pulse-sinks.txt 2>/dev/null; then
  echo "[start-audio] ERROR: onebridge sink not created" >&2
  cat /tmp/pulse-sink.log >&2 || true
  exit 1
fi

if ! ffmpeg -y -f pulse -i onebridge.monitor -t 0.2 -f null - >/tmp/ffmpeg-probe.log 2>&1; then
  echo "[start-audio] ERROR: ffmpeg cannot capture onebridge.monitor" >&2
  cat /tmp/ffmpeg-probe.log >&2 || true
  exit 1
fi

# --- heal audio-stream (only restart if not listening) ---
export PULSE_MONITOR=onebridge.monitor
export PULSE_SERVER

if ! stream_listening; then
  pkill -f "audio-stream.mjs" 2>/dev/null || true
  sleep 0.2
  nohup env PULSE_SERVER="$PULSE_SERVER" PULSE_MONITOR="$PULSE_MONITOR" \
    AUDIO_WS_PORT="$AUDIO_WS_PORT" \
    HOME="$HOME" XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
    PULSE_RUNTIME_PATH="$PULSE_RUNTIME_PATH" \
    node /opt/bridge/audio-stream.mjs >/tmp/audio-stream.log 2>&1 &
  for _ in $(seq 1 20); do
    if stream_listening; then
      break
    fi
    sleep 0.2
  done
fi

if ! stream_listening; then
  echo "[start-audio] ERROR: audio-stream did not listen on :${AUDIO_WS_PORT}" >&2
  cat /tmp/audio-stream.log >&2 || true
  exit 1
fi

echo "[start-audio] OK pulse + audio-stream on :${AUDIO_WS_PORT} (PULSE_SERVER=$PULSE_SERVER)"
exit 0
